# set these environment variables on your prod server
production:
  host: <%=ENV['OPENSHIFT_DB_HOST']%>
  port: <%=ENV['OPENSHIFT_DB_PORT']%>
  username: <%=ENV['OPENSHIFT_DB_USERNAME']%>
  password: <%=ENV['OPENSHIFT_DB_PASSWORD']%>
  socket: <%=ENV['OPENSHIFT_DB_SOCKET']%>
