# set these environment variables on your prod server
production:
  host: <%=ENV['OPENSHIFT_NOSQL_DB_HOST']%>
  port: <%=ENV['OPENSHIFT_NOSQL_DB_PORT']%>
  username: <%=ENV['OPENSHIFT_NOSQL_DB_USERNAME']%>
  password: <%=ENV['OPENSHIFT_NOSQL_DB_PASSWORD']%>
  database: <%= ENV['OPENSHIFT_APP_NAME'] %>
